% Code accompanying Zimmerman et al (GRL, 2024)
%
% Summary: 
% analytic equilibrium solutions of hosing (H) as a function of AMOC 
% transport (q), and gyre transport strengths (KN,KS) for 5-box model. Does 
% not run independently. Called by Analytic_DeltaH.m
%
%          
% Output:
%   - Hpos(q,KN,KS) (solution of hosing (H) for positive AMOC transport (q))
%   - Hneg(q,KN,KS) (solution of hosing (H) for negative AMOC transport (q))
%
% -------------------------------------------------------------------------
% Clark Zimmerman (cczimmerman3@wisc.edu) 
% Till Wagner (till.wagner@wisc.edu)
% October 2024
% -------------------------------------------------------------------------
% solutions of H as a function of q (from Mathematica) for 5-box model

%redefine some variables for simpler equations
DT=T0-TS;G1=gam-1;
AL=a*l;ALT=AL*(T0-TS);
ALM=AL*mu;ALM1=ALM+1;
BL0=b*l*S0;

%steady state solution for hosing (H) when AMOC strength (Q) is positive
Hpos=@(q,KN,KS) (eta*G1.*q.*(KN.*(KS.*(ALM.*q+ALT+q)+q.^2*ALM1+q*ALT+BL0.*(FIP+FN0+FT0))+...
    q.*(q.^2*ALM1+q*ALT+BL0.*(FIP+FN0+FT0))+KS.*(q.^2*ALM1+q*ALT+BL0.*FN0))-...
    eta*KIP.*(KN.*(KS.*(ALM.*q+ALT+q)+q.^2*ALM1+q*ALT+BL0.*(FN0+FT0))+...
    q.*(q.^2*ALM1+q*ALT+BL0.*(FN0+FT0))+KS.*(q.^2*ALM1+q*ALT+BL0.*FN0))+...
    G1.*q.*(2*KIP.*(KN.*(KS.*(ALM.*q+ALT+q)+q.^2*ALM1+q*ALT+BL0.*(FN0+FT0))+...
    q.*(q.^2*ALM1+q*ALT+BL0.*(FN0+FT0))+KS.*(q.^2*ALM1+q*ALT+BL0.*FN0))-...
    G1.*q.*(KN.*(2*KS.*(ALM.*q+ALT+q)+q.^2*ALM1+q*ALT+BL0.*(FIP+FN0-FS+FT0))+...
    q.*(q.^2*ALM1+q*ALT+BL0.*(FIP+FN0-FS+FT0))+2*KS.*(q.^2*ALM1+q*ALT+BL0.*FN0))))./...
    (BL0.*(eta*((KN+q).*(hosF_T.*KIP-G1.*q.*(hosF_IP+hosF_T))+hosF_N.*(-(gam.*q)+KIP+q).*(KN+KS+q))+G1.*...
    q.*((KN+q).*(G1.*q.*(hosF_IP-hosF_S+hosF_T)-2*hosF_T.*KIP)+hosF_N.*(G1.*q.*(KN+2*KS+q)-2*KIP.*(KN+KS+q)))));

%steady state solution for hosing (H) when AMOC strength (Q) is negative
Hneg=@(q,KN,KS) (-eta.*(KIP+G1.*q).*(-((KS-q).*(ALM1.*q.^2-BL0.*FN0+AL.*q.*DT))+...
    KN.*(-(ALM1.*q.^2)+BL0.*(FN0+FT0)+KS.*(q+ALM.*q+ALT)+AL.*q.*(-T0+TS)))+...
    q.*(G1.*q.*(KN.*(-BL0.*FS+KS.*(q+ALM.*q+ALT)-...
    gam.*q.*(q+ALM.*q+ALT))+q.*(BL0.*FS+gam.*(ALM1.*q.^2+BL0.*FT0+AL.*q.*DT))-...
    KS.*(ALM1.*q.^2+BL0.*(FS+FT0)+AL.*q.*DT))+...
    KIP.*(-((KS-q).*(ALM1.*q.^2-BL0.*FN0+AL.*q.*DT))+...
    KN.*(-(ALM1.*q.^2)+BL0.*(FN0+FT0)+KS.*(q+ALM.*q+ALT)+AL.*q.*(-T0+TS)))))./...
    (BL0.*(eta.*(hosF_T.*KN+hosF_N.*(KN+KS-q)).*(KIP+G1.*q)-q.*(hosF_T.*KIP.*KN+...
    hosF_N.*KIP.*(KN+KS-q)-G1.*(hosF_T.*KS+hosF_S.*(KN+KS)).*q+G1.*(hosF_S+gam.*hosF_T).*q.^2)));